version: "3.8"
services:
  application:
    build:
      context: "."
      dockerfile: Dockerfile
      network: host
    environment:
      - TZ=America/Sao_Paulo
    container_name: java-spring_template
    ports:
      - 5000:8080
    volumes:
      - "../:/app"
      - "${HOME}/.m2:/root/.m2"
    working_dir: /app
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: hustle-tech